### ISSUE TITLE
serverKnowledge missing from most responses

### ISSUE THREAD

**Issue by a2rpriest** [andrebocchini/swiftynab#10]
Hi, first thank you so much for making this wonderful package!

I have a quick question: why don't more items have "serverKnowledge" in their response? It seems super useful to request only things that have changed on a BudgetDetail since the last server knowledge, but I don't see a way to get that "serverKnowledge" Int from the BudgetDetailResponse and store it like there is with the AccountsResponse struct. Could you help me understand why this is the case?

I'm new to API stuff, so thank you for your patience.

**Comment by andrebocchini** [comment]
I made this a while back to serve a project I was working on, but I haven't used it recently. I honestly don't remember the reason. It's entirely possible that those properties weren't there at the time, or that I just missed them/didn't need them. 

I can take a look and see if I have some time to add them, but you can also feel free to make a pull request if you want to give it a shot.
