### ISSUE TITLE
Unable to add package

### ISSUE THREAD

**Issue by iwaddo** [andrebocchini/swiftynab#8]
I am not sure if this is the correct way to ask for help so apologies in advance if not.  I have tried adding the package to my project put continuously receive the following error which I have no idea of how to resolve.

Any help appreciated.

Showing Recent Messages
invalidManifestFormat("/var/folders/st/zlvsrg1d3mg3ctxx6j8fzfmc0000gn/T/TemporaryFile.M9cbby.swift:23:17: error: expected \',\' separator\n            path: \"SwiftYNAB/SwiftYNABTests\"\n                ^\n                ,\n/var/folders/st/zlvsrg1d3mg3ctxx6j8fzfmc0000gn/T/TemporaryFile.M9cbby.swift:23:17: error: expected expression in container literal\n            path: \"SwiftYNAB/SwiftYNABTests\"\n                ^\n/var/folders/st/zlvsrg1d3mg3ctxx6j8fzfmc0000gn/T/TemporaryFile.M9cbby.swift:23:13: error: cannot find \'path\' in scope\n            path: \"SwiftYNAB/SwiftYNABTests\"\n            ^~~~", diagnosticFile: Optional(<AbsolutePath:"/Users/NameOfMyMac/Library/Developer/Xcode/DerivedData/YNABSwiftTest-bupfkjycbrorbrhaxbvtsuhngojm/SourcePackages/ManifestLoading/swiftynab.dia">)) in https://github.com/andrebocchini/swiftynab

**Comment by johnedquinn** [comment]
Same here -- getting the same issue with v2.0. Able to import 1.1.1, but 2.0 fails with the same message.

**Comment by brantonb** [comment]
This was a really easy fix, so I opened a PR for it.
